name: Build-Full

on:
  workflow_dispatch:

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt; 
      - name: Compile
        run: |
          pyinstaller -F CDNDrive/__main__.py -i icon.ico --distpath output -n cdrive
          pyinstaller -F CDNDrive/__main__downloadonly.py -i icon.ico --distpath output/download_only_version -n cdrive
      - name: Upload
        uses: actions/upload-artifact@v3.1.0
        with:
          name: cdrive-linux
          path: output
  
  windows-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
      - name: Compile
        run: |
          pyinstaller -F CDNDrive/__main__.py -i icon.ico --distpath output -n cdrive
          pyinstaller -F CDNDrive/__main__downloadonly.py -i icon.ico --distpath output/download_only_version -n cdrive
      - name: Upload
        uses: actions/upload-artifact@v3.1.0
        with:
          name: cdrive-windows
          path: output
          
  macos-build:
    runs-on: macos-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v3
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v4.0.0
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
      - name: Compile
        run: |
          pyinstaller -F CDNDrive/__main__.py -i icon.ico --distpath output -n cdrive
          pyinstaller -F CDNDrive/__main__downloadonly.py -i icon.ico --distpath output/download_only_version -n cdrive
      - name : Upload
        uses: actions/upload-artifact@v3.1.0
        with:
          name: cdrive-macos
          path: output
